"""
models/incident.py

SQLAlchemy ORM models for the Incident Management module.

Tables:
    incidents           — core incident record
    incident_timeline   — audit trail for every action on an incident
    incident_ai_triage  — Gemini AI triage suggestion per incident
"""

from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Enum, DECIMAL
from sqlalchemy.dialects.mysql import BIGINT
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from config.database import Base


# ------------------------------------------------------------------ #
# Incident
# ------------------------------------------------------------------ #

class Incident(Base):
    """An operational incident reported by a user."""

    __tablename__ = "incidents"

    id = Column(BIGINT(unsigned=True), primary_key=True, autoincrement=True)

    reported_by = Column(
        BIGINT(unsigned=True),
        ForeignKey("users.id", onupdate="CASCADE", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    assigned_to = Column(
        BIGINT(unsigned=True),
        ForeignKey("users.id", onupdate="CASCADE", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    title           = Column(String(255), nullable=False)
    description     = Column(Text,        nullable=False)
    affected_system = Column(String(120),  nullable=True)
    root_cause      = Column(Text,         nullable=True)

    severity = Column(
        Enum("low", "medium", "high", "critical"),
        nullable=False,
        default="medium",
        index=True,
    )
    status = Column(
        Enum("open", "investigating", "resolved", "closed"),
        nullable=False,
        default="open",
        index=True,
    )

    resolved_at = Column(DateTime(timezone=True), nullable=True)
    created_at  = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at  = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    reporter  = relationship("User", foreign_keys=[reported_by])
    assignee  = relationship("User", foreign_keys=[assigned_to])
    timeline  = relationship(
        "IncidentTimeline",
        back_populates="incident",
        order_by="IncidentTimeline.created_at",
        cascade="all, delete-orphan",
    )
    ai_triages = relationship(
        "IncidentAITriage",
        back_populates="incident",
        order_by="IncidentAITriage.generated_at.desc()",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Incident id={self.id} severity={self.severity!r} status={self.status!r}>"


# ------------------------------------------------------------------ #
# IncidentTimeline — audit trail
# ------------------------------------------------------------------ #

class IncidentTimeline(Base):
    """Every status change, comment, or AI action on an incident."""

    __tablename__ = "incident_timeline"

    id          = Column(BIGINT(unsigned=True), primary_key=True, autoincrement=True)
    incident_id = Column(
        BIGINT(unsigned=True),
        ForeignKey("incidents.id", onupdate="CASCADE", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # NULL = AI-generated action (matches schema design)
    actor_id = Column(
        BIGINT(unsigned=True),
        ForeignKey("users.id", onupdate="CASCADE", ondelete="SET NULL"),
        nullable=True,
    )
    action     = Column(String(80), nullable=False)   # e.g. 'incident_created'
    notes      = Column(Text,       nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    incident = relationship("Incident", back_populates="timeline")
    actor    = relationship("User", foreign_keys=[actor_id])

    def __repr__(self) -> str:
        return f"<IncidentTimeline id={self.id} action={self.action!r}>"


# ------------------------------------------------------------------ #
# IncidentAITriage — Gemini suggestion per incident
# ------------------------------------------------------------------ #

class IncidentAITriage(Base):
    """AI triage suggestion generated by Gemini for an incident."""

    __tablename__ = "incident_ai_triage"

    id          = Column(BIGINT(unsigned=True), primary_key=True, autoincrement=True)
    incident_id = Column(
        BIGINT(unsigned=True),
        ForeignKey("incidents.id", onupdate="CASCADE", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    suggested_severity = Column(String(20),       nullable=False)
    suggested_owner    = Column(String(120),       nullable=True)
    reasoning          = Column(Text,              nullable=False)
    confidence         = Column(DECIMAL(5, 2),     nullable=True)   # 0.00 – 100.00
    ai_model           = Column(String(60),        nullable=False, default="gemini-3.6-flash")
    generated_at       = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    incident = relationship("Incident", back_populates="ai_triages")

    def __repr__(self) -> str:
        return (
            f"<IncidentAITriage id={self.id} "
            f"severity={self.suggested_severity!r} confidence={self.confidence}>"
        )
