-- =============================================================================
-- Unified AI for Enterprise Automation
-- PostgreSQL Database Schema
-- Version: 2.0  (migrated from MySQL)
-- =============================================================================
-- This file is a human-readable reference snapshot of the schema.
-- The AUTHORITATIVE source of truth is the Alembic migrations in
-- backend/migrations/versions/. Apply them with:
--
--     cd backend && alembic upgrade head
--
-- Keep this file in sync when you add a migration.
-- -----------------------------------------------------------------------------
-- Conventions:
--   Tables     : snake_case, plural
--   PKs        : id  (BIGINT GENERATED BY DEFAULT AS IDENTITY; roles uses INT)
--   FKs        : <table_singular>_id
--   Timestamps : created_at, updated_at (updated_at maintained by trigger + ORM)
--   Soft delete: deleted_at (NULL = active)
--   Enums      : native PostgreSQL ENUM types, named <table_singular>_<field>
-- =============================================================================

-- To create the database and role manually (docker-compose.yml does this for you):
--   CREATE ROLE enterprise WITH LOGIN PASSWORD 'enterprise';
--   CREATE DATABASE enterprise_ai OWNER enterprise;

-- =============================================================================
-- Shared helper: keep updated_at fresh on UPDATE
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 1. AUTHENTICATION & RBAC
-- =============================================================================

-- Roles catalogue
CREATE TABLE roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)   NOT NULL UNIQUE,
    description TEXT          NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_roles_name ON roles (name);

-- Application users
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         INTEGER      NOT NULL
                        REFERENCES roles (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    full_name       VARCHAR(120) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ  NULL
);
CREATE INDEX ix_users_role_id ON users (role_id);
CREATE INDEX ix_users_email   ON users (email);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 2. EMPLOYEE MANAGEMENT
-- =============================================================================

CREATE TYPE employee_employment_type AS ENUM ('full_time', 'part_time', 'contract', 'intern');
CREATE TYPE employee_status          AS ENUM ('active', 'inactive', 'on_leave', 'terminated');

CREATE TABLE employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE
                        REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    department_id   INTEGER      NULL,          -- departments table not yet modelled
    employee_code   VARCHAR(30)  NOT NULL UNIQUE,
    job_title       VARCHAR(100) NOT NULL,
    phone           VARCHAR(30)  NULL,
    hire_date       DATE         NOT NULL,
    employment_type employee_employment_type NOT NULL DEFAULT 'full_time',
    status          employee_status          NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ  NULL
);
CREATE INDEX ix_employees_user_id       ON employees (user_id);
CREATE INDEX ix_employees_department_id ON employees (department_id);
CREATE INDEX ix_employees_status        ON employees (status);
CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON employees
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 3. RECRUITMENT AI
-- =============================================================================

CREATE TYPE job_posting_experience_level AS ENUM ('entry', 'junior', 'mid', 'senior', 'lead');
CREATE TYPE job_posting_status           AS ENUM ('draft', 'active', 'closed');

CREATE TABLE job_postings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by       BIGINT       NOT NULL
                         REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    title            VARCHAR(150) NOT NULL,
    description      TEXT         NULL,
    required_skills  TEXT         NOT NULL,
    min_education    VARCHAR(100) NOT NULL DEFAULT 'Bachelor''s Degree',
    experience_level job_posting_experience_level NOT NULL DEFAULT 'mid',
    status           job_posting_status           NOT NULL DEFAULT 'active',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_job_postings_created_by ON job_postings (created_by);
CREATE INDEX ix_job_postings_status     ON job_postings (status);
CREATE TRIGGER trg_job_postings_updated_at BEFORE UPDATE ON job_postings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TYPE resume_recommendation AS ENUM ('selected', 'hold', 'rejected');
CREATE TYPE resume_status         AS ENUM ('uploaded', 'extracted', 'analysed', 'error');

CREATE TABLE resumes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id  BIGINT       NOT NULL
                        REFERENCES job_postings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    candidate_name  VARCHAR(120) NOT NULL,
    candidate_email VARCHAR(255) NULL,
    file_name       VARCHAR(255) NOT NULL,
    file_path       VARCHAR(512) NOT NULL,
    extracted_text  TEXT         NULL,
    ai_score        DOUBLE PRECISION NULL,
    ai_summary      TEXT         NULL,
    strengths       TEXT         NULL,
    missing_skills  TEXT         NULL,
    recommendation  resume_recommendation NULL,
    status          resume_status         NOT NULL DEFAULT 'uploaded',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_resumes_job_posting_id  ON resumes (job_posting_id);
CREATE INDEX ix_resumes_candidate_email ON resumes (candidate_email);
CREATE INDEX ix_resumes_status          ON resumes (status);
CREATE TRIGGER trg_resumes_updated_at BEFORE UPDATE ON resumes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TYPE candidate_status AS ENUM ('applied', 'screening', 'interview', 'offer', 'hired', 'rejected');

CREATE TABLE candidates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id INTEGER      NULL,           -- loose reference (no FK), legacy
    full_name      VARCHAR(120) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    phone          VARCHAR(30)  NULL,
    resume_path    VARCHAR(512) NULL,
    linkedin_url   VARCHAR(512) NULL,
    ai_score       NUMERIC(5, 2) NULL,
    status         candidate_status NOT NULL DEFAULT 'applied',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_candidates_job_posting_id ON candidates (job_posting_id);
CREATE INDEX ix_candidates_email          ON candidates (email);
CREATE INDEX ix_candidates_status         ON candidates (status);
CREATE TRIGGER trg_candidates_updated_at BEFORE UPDATE ON candidates
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 4. CUSTOMER SUPPORT AI
-- =============================================================================

CREATE TYPE support_ticket_priority AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE support_ticket_status   AS ENUM ('open', 'in_progress', 'resolved', 'closed', 'escalated');
CREATE TYPE support_ticket_channel  AS ENUM ('web', 'email', 'chat', 'api');

CREATE TABLE support_tickets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by BIGINT       NOT NULL
                     REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    assigned_to  BIGINT       NULL
                     REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    subject      VARCHAR(255) NOT NULL,
    description  TEXT         NOT NULL,
    priority     support_ticket_priority NOT NULL DEFAULT 'medium',
    status       support_ticket_status   NOT NULL DEFAULT 'open',
    channel      support_ticket_channel  NOT NULL DEFAULT 'web',
    resolved_at  TIMESTAMPTZ  NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_support_tickets_submitted_by ON support_tickets (submitted_by);
CREATE INDEX ix_support_tickets_assigned_to  ON support_tickets (assigned_to);
CREATE INDEX ix_support_tickets_priority     ON support_tickets (priority);
CREATE INDEX ix_support_tickets_status       ON support_tickets (status);
CREATE TRIGGER trg_support_tickets_updated_at BEFORE UPDATE ON support_tickets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 5. INCIDENT MANAGEMENT
-- =============================================================================

CREATE TYPE incident_severity AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE incident_status   AS ENUM ('open', 'investigating', 'resolved', 'closed');

CREATE TABLE incidents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reported_by     BIGINT       NOT NULL
                        REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    assigned_to     BIGINT       NULL
                        REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT         NOT NULL,
    affected_system VARCHAR(120) NULL,
    root_cause      TEXT         NULL,
    severity        incident_severity NOT NULL DEFAULT 'medium',
    status          incident_status   NOT NULL DEFAULT 'open',
    resolved_at     TIMESTAMPTZ  NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_incidents_reported_by ON incidents (reported_by);
CREATE INDEX ix_incidents_assigned_to ON incidents (assigned_to);
CREATE INDEX ix_incidents_severity    ON incidents (severity);
CREATE INDEX ix_incidents_status      ON incidents (status);
CREATE TRIGGER trg_incidents_updated_at BEFORE UPDATE ON incidents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 6. MEETING INTELLIGENCE   (offline processing — feature/meeting-offline)
-- =============================================================================
-- The uploaded video stays on local disk; only its path is stored here.

CREATE TYPE meeting_status AS ENUM
    ('pending', 'processing', 'extracting_audio', 'transcribing', 'diarizing', 'analyzing', 'completed', 'failed');

CREATE TABLE meetings (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by             BIGINT        NOT NULL
                               REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    title                  VARCHAR(255)  NOT NULL,
    description            TEXT          NULL,
    meeting_date           TIMESTAMPTZ   NULL,
    source_video_path      VARCHAR(1024) NULL,          -- local filesystem path (never the blob)
    source_video_filename  VARCHAR(512)  NULL,
    source_media_type      VARCHAR(100)  NULL,
    file_size_bytes        BIGINT        NULL,
    audio_path             VARCHAR(1024) NULL,          -- extracted WAV, also on disk
    duration_sec           INTEGER       NULL,
    language               VARCHAR(16)   NULL,
    status                 meeting_status NOT NULL DEFAULT 'pending',
    error_message          TEXT          NULL,
    processing_started_at  TIMESTAMPTZ   NULL,
    processing_finished_at TIMESTAMPTZ   NULL,
    whisper_model          VARCHAR(50)   NULL,
    diarization_backend    VARCHAR(50)   NULL,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_meetings_created_by ON meetings (created_by);
CREATE INDEX ix_meetings_status     ON meetings (status);
CREATE TRIGGER trg_meetings_updated_at BEFORE UPDATE ON meetings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Manually-added attendees (may link to a user and/or employee)
CREATE TYPE meeting_participant_role AS ENUM ('organizer', 'attendee', 'guest');

CREATE TABLE meeting_participants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id   BIGINT       NOT NULL
                     REFERENCES meetings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    user_id      BIGINT       NULL
                     REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    employee_id  BIGINT       NULL
                     REFERENCES employees (id) ON UPDATE CASCADE ON DELETE SET NULL,
    display_name VARCHAR(255) NOT NULL,
    role         meeting_participant_role NOT NULL DEFAULT 'attendee',
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_meeting_participant_user UNIQUE (meeting_id, user_id)
);
CREATE INDEX ix_meeting_participants_meeting_id  ON meeting_participants (meeting_id);
CREATE INDEX ix_meeting_participants_user_id     ON meeting_participants (user_id);
CREATE INDEX ix_meeting_participants_employee_id ON meeting_participants (employee_id);

-- Diarization-detected voices ("Speaker 1"); optional mapping to a real person
CREATE TABLE meeting_speakers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id         BIGINT       NOT NULL
                           REFERENCES meetings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    label              VARCHAR(50)  NOT NULL,          -- "Speaker 1"
    display_name       VARCHAR(255) NULL,
    mapped_user_id     BIGINT       NULL
                           REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    mapped_employee_id BIGINT       NULL
                           REFERENCES employees (id) ON UPDATE CASCADE ON DELETE SET NULL,
    total_speaking_sec INTEGER      NULL,
    segment_count      INTEGER      NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_meeting_speaker_label UNIQUE (meeting_id, label)
);
CREATE INDEX ix_meeting_speakers_meeting_id         ON meeting_speakers (meeting_id);
CREATE INDEX ix_meeting_speakers_mapped_user_id     ON meeting_speakers (mapped_user_id);
CREATE INDEX ix_meeting_speakers_mapped_employee_id ON meeting_speakers (mapped_employee_id);
CREATE TRIGGER trg_meeting_speakers_updated_at BEFORE UPDATE ON meeting_speakers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Full-text transcript (1:1 with meetings)
CREATE TABLE meeting_transcripts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id     BIGINT      NOT NULL UNIQUE
                       REFERENCES meetings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    full_text      TEXT        NOT NULL,
    language       VARCHAR(16) NULL,
    whisper_model  VARCHAR(50) NULL,
    word_count     INTEGER     NULL,
    segment_count  INTEGER     NULL,
    transcribed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Diarized, timestamped transcript segments
CREATE TABLE meeting_transcript_segments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id    BIGINT      NOT NULL
                      REFERENCES meetings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    speaker_id    BIGINT      NULL
                      REFERENCES meeting_speakers (id) ON UPDATE CASCADE ON DELETE SET NULL,
    speaker_label VARCHAR(50) NULL,                    -- denormalised from meeting_speakers
    seq           INTEGER     NOT NULL,
    start_ms      INTEGER     NOT NULL,
    end_ms        INTEGER     NOT NULL,
    text          TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_meeting_transcript_segments_meeting_id  ON meeting_transcript_segments (meeting_id);
CREATE INDEX ix_meeting_transcript_segments_speaker_id  ON meeting_transcript_segments (speaker_id);
CREATE INDEX ix_meeting_transcript_segments_meeting_seq ON meeting_transcript_segments (meeting_id, seq);

-- Structured AI analysis (1:1 with meetings)
CREATE TABLE meeting_analyses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id     BIGINT       NOT NULL UNIQUE
                       REFERENCES meetings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    summary        TEXT         NOT NULL,
    key_points     JSON         NULL,                  -- ["point", ...]
    decisions      JSON         NULL,                  -- ["decision", ...]
    sentiment      VARCHAR(20)  NULL,
    model_provider VARCHAR(50)  NOT NULL DEFAULT 'gemini',
    model_name     VARCHAR(100) NULL,
    raw_response   JSON         NULL,                  -- full provider payload for audit
    prompt_tokens  INTEGER      NULL,
    generated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Action items — AI-extracted, MANUALLY assigned in the MVP.
-- assignee_name_raw + ai_confidence + assignment_method keep the door open for
-- automatic AI assignment later with no schema change.
CREATE TYPE meeting_action_item_assignment_method AS ENUM ('unassigned', 'manual', 'ai');
CREATE TYPE meeting_action_item_priority          AS ENUM ('low', 'medium', 'high');
CREATE TYPE meeting_action_item_status            AS ENUM ('pending', 'in_progress', 'completed', 'cancelled');
CREATE TYPE meeting_action_item_source            AS ENUM ('ai', 'manual');

CREATE TABLE meeting_action_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id              BIGINT       NOT NULL
                                REFERENCES meetings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    analysis_id             BIGINT       NULL
                                REFERENCES meeting_analyses (id) ON UPDATE CASCADE ON DELETE SET NULL,
    description             TEXT         NOT NULL,
    assigned_to_user_id     BIGINT       NULL
                                REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    assigned_to_employee_id BIGINT       NULL
                                REFERENCES employees (id) ON UPDATE CASCADE ON DELETE SET NULL,
    assignee_name_raw       VARCHAR(255) NULL,         -- raw AI mention, NOT resolved
    assignment_method       meeting_action_item_assignment_method NOT NULL DEFAULT 'unassigned',
    due_date                DATE         NULL,
    priority                meeting_action_item_priority NULL,
    status                  meeting_action_item_status   NOT NULL DEFAULT 'pending',
    source                  meeting_action_item_source   NOT NULL DEFAULT 'ai',
    ai_confidence           DOUBLE PRECISION NULL,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_meeting_action_items_meeting_id              ON meeting_action_items (meeting_id);
CREATE INDEX ix_meeting_action_items_analysis_id             ON meeting_action_items (analysis_id);
CREATE INDEX ix_meeting_action_items_assigned_to_user_id     ON meeting_action_items (assigned_to_user_id);
CREATE INDEX ix_meeting_action_items_assigned_to_employee_id ON meeting_action_items (assigned_to_employee_id);
CREATE INDEX ix_meeting_action_items_status                  ON meeting_action_items (status);
CREATE TRIGGER trg_meeting_action_items_updated_at BEFORE UPDATE ON meeting_action_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- SEED: default roles  (also performed by the initial Alembic migration)
-- =============================================================================
INSERT INTO roles (name, description) VALUES
    ('admin',         'Full system access'),
    ('hr_manager',    'Employee and recruitment management'),
    ('support_agent', 'Customer support ticket handling'),
    ('recruiter',     'Recruitment pipeline management'),
    ('employee',      'Standard employee self-service access'),
    ('viewer',        'Read-only analytics access')
ON CONFLICT (name) DO NOTHING;
