-- =============================================================================
-- Unified AI for Enterprise Automation
-- PostgreSQL Database Schema
-- Version: 2.0  (migrated from MySQL)
-- =============================================================================
-- This file is a human-readable reference snapshot of the schema.
-- The AUTHORITATIVE source of truth is the Alembic migrations in
-- backend/migrations/versions/. Apply them with:
--
--     cd backend && alembic upgrade head
--
-- Keep this file in sync when you add a migration.
-- -----------------------------------------------------------------------------
-- Conventions:
--   Tables     : snake_case, plural
--   PKs        : id  (BIGINT GENERATED BY DEFAULT AS IDENTITY; roles uses INT)
--   FKs        : <table_singular>_id
--   Timestamps : created_at, updated_at (updated_at maintained by trigger + ORM)
--   Soft delete: deleted_at (NULL = active)
--   Enums      : native PostgreSQL ENUM types, named <table_singular>_<field>
-- =============================================================================

-- To create the database and role manually (docker-compose.yml does this for you):
--   CREATE ROLE enterprise WITH LOGIN PASSWORD 'enterprise';
--   CREATE DATABASE enterprise_ai OWNER enterprise;

-- =============================================================================
-- Shared helper: keep updated_at fresh on UPDATE
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 1. AUTHENTICATION & RBAC
-- =============================================================================

-- Roles catalogue
CREATE TABLE roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)   NOT NULL UNIQUE,
    description TEXT          NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_roles_name ON roles (name);

-- Application users
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         INTEGER      NOT NULL
                        REFERENCES roles (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    full_name       VARCHAR(120) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ  NULL
);
CREATE INDEX ix_users_role_id ON users (role_id);
CREATE INDEX ix_users_email   ON users (email);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 2. EMPLOYEE MANAGEMENT
-- =============================================================================

CREATE TYPE employee_employment_type AS ENUM ('full_time', 'part_time', 'contract', 'intern');
CREATE TYPE employee_status          AS ENUM ('active', 'inactive', 'on_leave', 'terminated');

CREATE TABLE employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE
                        REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    department_id   INTEGER      NULL,          -- departments table not yet modelled
    employee_code   VARCHAR(30)  NOT NULL UNIQUE,
    job_title       VARCHAR(100) NOT NULL,
    phone           VARCHAR(30)  NULL,
    hire_date       DATE         NOT NULL,
    employment_type employee_employment_type NOT NULL DEFAULT 'full_time',
    status          employee_status          NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ  NULL
);
CREATE INDEX ix_employees_user_id       ON employees (user_id);
CREATE INDEX ix_employees_department_id ON employees (department_id);
CREATE INDEX ix_employees_status        ON employees (status);
CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON employees
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 3. RECRUITMENT AI
-- =============================================================================

CREATE TYPE job_posting_experience_level AS ENUM ('entry', 'junior', 'mid', 'senior', 'lead');
CREATE TYPE job_posting_status           AS ENUM ('draft', 'active', 'closed');

CREATE TABLE job_postings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by       BIGINT       NOT NULL
                         REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    title            VARCHAR(150) NOT NULL,
    description      TEXT         NULL,
    required_skills  TEXT         NOT NULL,
    min_education    VARCHAR(100) NOT NULL DEFAULT 'Bachelor''s Degree',
    experience_level job_posting_experience_level NOT NULL DEFAULT 'mid',
    status           job_posting_status           NOT NULL DEFAULT 'active',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_job_postings_created_by ON job_postings (created_by);
CREATE INDEX ix_job_postings_status     ON job_postings (status);
CREATE TRIGGER trg_job_postings_updated_at BEFORE UPDATE ON job_postings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TYPE resume_recommendation AS ENUM ('selected', 'hold', 'rejected');
CREATE TYPE resume_status         AS ENUM ('uploaded', 'extracted', 'analysed', 'error');

CREATE TABLE resumes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id  BIGINT       NOT NULL
                        REFERENCES job_postings (id) ON UPDATE CASCADE ON DELETE CASCADE,
    candidate_name  VARCHAR(120) NOT NULL,
    candidate_email VARCHAR(255) NULL,
    file_name       VARCHAR(255) NOT NULL,
    file_path       VARCHAR(512) NOT NULL,
    extracted_text  TEXT         NULL,
    ai_score        DOUBLE PRECISION NULL,
    ai_summary      TEXT         NULL,
    strengths       TEXT         NULL,
    missing_skills  TEXT         NULL,
    recommendation  resume_recommendation NULL,
    status          resume_status         NOT NULL DEFAULT 'uploaded',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_resumes_job_posting_id  ON resumes (job_posting_id);
CREATE INDEX ix_resumes_candidate_email ON resumes (candidate_email);
CREATE INDEX ix_resumes_status          ON resumes (status);
CREATE TRIGGER trg_resumes_updated_at BEFORE UPDATE ON resumes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TYPE candidate_status AS ENUM ('applied', 'screening', 'interview', 'offer', 'hired', 'rejected');

CREATE TABLE candidates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id INTEGER      NULL,           -- loose reference (no FK), legacy
    full_name      VARCHAR(120) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    phone          VARCHAR(30)  NULL,
    resume_path    VARCHAR(512) NULL,
    linkedin_url   VARCHAR(512) NULL,
    ai_score       NUMERIC(5, 2) NULL,
    status         candidate_status NOT NULL DEFAULT 'applied',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_candidates_job_posting_id ON candidates (job_posting_id);
CREATE INDEX ix_candidates_email          ON candidates (email);
CREATE INDEX ix_candidates_status         ON candidates (status);
CREATE TRIGGER trg_candidates_updated_at BEFORE UPDATE ON candidates
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 4. CUSTOMER SUPPORT AI
-- =============================================================================

CREATE TYPE support_ticket_priority AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE support_ticket_status   AS ENUM ('open', 'in_progress', 'resolved', 'closed', 'escalated');
CREATE TYPE support_ticket_channel  AS ENUM ('web', 'email', 'chat', 'api');

CREATE TABLE support_tickets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by BIGINT       NOT NULL
                     REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    assigned_to  BIGINT       NULL
                     REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    subject      VARCHAR(255) NOT NULL,
    description  TEXT         NOT NULL,
    priority     support_ticket_priority NOT NULL DEFAULT 'medium',
    status       support_ticket_status   NOT NULL DEFAULT 'open',
    channel      support_ticket_channel  NOT NULL DEFAULT 'web',
    resolved_at  TIMESTAMPTZ  NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_support_tickets_submitted_by ON support_tickets (submitted_by);
CREATE INDEX ix_support_tickets_assigned_to  ON support_tickets (assigned_to);
CREATE INDEX ix_support_tickets_priority     ON support_tickets (priority);
CREATE INDEX ix_support_tickets_status       ON support_tickets (status);
CREATE TRIGGER trg_support_tickets_updated_at BEFORE UPDATE ON support_tickets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 5. INCIDENT MANAGEMENT
-- =============================================================================

CREATE TYPE incident_severity AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE incident_status   AS ENUM ('open', 'investigating', 'resolved', 'closed');

CREATE TABLE incidents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reported_by     BIGINT       NOT NULL
                        REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    assigned_to     BIGINT       NULL
                        REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT         NOT NULL,
    affected_system VARCHAR(120) NULL,
    root_cause      TEXT         NULL,
    severity        incident_severity NOT NULL DEFAULT 'medium',
    status          incident_status   NOT NULL DEFAULT 'open',
    resolved_at     TIMESTAMPTZ  NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_incidents_reported_by ON incidents (reported_by);
CREATE INDEX ix_incidents_assigned_to ON incidents (assigned_to);
CREATE INDEX ix_incidents_severity    ON incidents (severity);
CREATE INDEX ix_incidents_status      ON incidents (status);
CREATE TRIGGER trg_incidents_updated_at BEFORE UPDATE ON incidents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 6. MEETING INTELLIGENCE
-- =============================================================================
-- Intentionally omitted here. The Meeting Intelligence module
-- (feature/meeting-offline) defines its tables in a dedicated Alembic
-- migration and will append them to this file at that time.

-- =============================================================================
-- SEED: default roles  (also performed by the initial Alembic migration)
-- =============================================================================
INSERT INTO roles (name, description) VALUES
    ('admin',         'Full system access'),
    ('hr_manager',    'Employee and recruitment management'),
    ('support_agent', 'Customer support ticket handling'),
    ('recruiter',     'Recruitment pipeline management'),
    ('employee',      'Standard employee self-service access'),
    ('viewer',        'Read-only analytics access')
ON CONFLICT (name) DO NOTHING;
