"""meeting intelligence tables

Revision ID: cfa33efa1872
Revises: 3785a3687963
Create Date: 2026-09-09 23:08:43.357084
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa33efa1872'
down_revision: Union[str, Sequence[str], None] = '3785a3687963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True, comment='When the meeting actually took place'),
    sa.Column('source_video_path', sa.String(length=1024), nullable=True, comment='Local filesystem path to the uploaded video'),
    sa.Column('source_video_filename', sa.String(length=512), nullable=True, comment='Original upload filename'),
    sa.Column('source_media_type', sa.String(length=100), nullable=True, comment='Detected MIME / container type'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=True, comment='Extracted 16 kHz mono WAV path'),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True, comment='Detected/forced language code'),
    sa.Column('status', sa.Enum('pending', 'extracting_audio', 'transcribing', 'diarizing', 'analyzing', 'completed', 'failed', name='meeting_status'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whisper_model', sa.String(length=50), nullable=True),
    sa.Column('diarization_backend', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('meeting_analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=True, comment='List of strings: ["point", ...]'),
    sa.Column('decisions', sa.JSON(), nullable=True, comment='List of strings: ["decision", ...]'),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('model_provider', sa.String(length=50), server_default='gemini', nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True, comment='Full provider payload for audit'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_analyses_meeting_id'), 'meeting_analyses', ['meeting_id'], unique=True)
    op.create_table('meeting_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('organizer', 'attendee', 'guest', name='meeting_participant_role'), server_default='attendee', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_participant_user')
    )
    op.create_index(op.f('ix_meeting_participants_employee_id'), 'meeting_participants', ['employee_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False)
    op.create_table('meeting_speakers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False, comment='Generic label, e.g. "Speaker 1"'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Editable friendly name set in the UI'),
    sa.Column('mapped_user_id', sa.BigInteger(), nullable=True),
    sa.Column('mapped_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('total_speaking_sec', sa.Integer(), nullable=True),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mapped_employee_id'], ['employees.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapped_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'label', name='uq_meeting_speaker_label')
    )
    op.create_index(op.f('ix_meeting_speakers_mapped_employee_id'), 'meeting_speakers', ['mapped_employee_id'], unique=False)
    op.create_index(op.f('ix_meeting_speakers_mapped_user_id'), 'meeting_speakers', ['mapped_user_id'], unique=False)
    op.create_index(op.f('ix_meeting_speakers_meeting_id'), 'meeting_speakers', ['meeting_id'], unique=False)
    op.create_table('meeting_transcripts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('whisper_model', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('transcribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_transcripts_meeting_id'), 'meeting_transcripts', ['meeting_id'], unique=True)
    op.create_table('meeting_action_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_to_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('assignee_name_raw', sa.String(length=255), nullable=True, comment='Raw assignee mention from the AI — NOT resolved to a person'),
    sa.Column('assignment_method', sa.Enum('unassigned', 'manual', 'ai', name='meeting_action_item_assignment_method'), server_default='unassigned', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='meeting_action_item_priority'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='meeting_action_item_status'), server_default='pending', nullable=False),
    sa.Column('source', sa.Enum('ai', 'manual', name='meeting_action_item_source'), server_default='ai', nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True, comment='0-1 confidence from the extractor'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['meeting_analyses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_employee_id'], ['employees.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_action_items_analysis_id'), 'meeting_action_items', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_assigned_to_employee_id'), 'meeting_action_items', ['assigned_to_employee_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_assigned_to_user_id'), 'meeting_action_items', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_meeting_id'), 'meeting_action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_status'), 'meeting_action_items', ['status'], unique=False)
    op.create_table('meeting_transcript_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker_id', sa.BigInteger(), nullable=True),
    sa.Column('speaker_label', sa.String(length=50), nullable=True, comment='Denormalised from meeting_speakers.label'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='0-based order within the meeting'),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['meeting_speakers.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_transcript_segments_meeting_id'), 'meeting_transcript_segments', ['meeting_id'], unique=False)
    op.create_index('ix_meeting_transcript_segments_meeting_seq', 'meeting_transcript_segments', ['meeting_id', 'seq'], unique=False)
    op.create_index(op.f('ix_meeting_transcript_segments_speaker_id'), 'meeting_transcript_segments', ['speaker_id'], unique=False)
    # ### end Alembic commands ###

    # --- updated_at maintenance (set_updated_at() created in the initial migration) ---
    for _table in ("meetings", "meeting_speakers", "meeting_action_items"):
        op.execute(
            f"CREATE TRIGGER trg_{_table}_updated_at BEFORE UPDATE ON {_table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    # Triggers are dropped automatically with their tables below.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_transcript_segments_speaker_id'), table_name='meeting_transcript_segments')
    op.drop_index('ix_meeting_transcript_segments_meeting_seq', table_name='meeting_transcript_segments')
    op.drop_index(op.f('ix_meeting_transcript_segments_meeting_id'), table_name='meeting_transcript_segments')
    op.drop_table('meeting_transcript_segments')
    op.drop_index(op.f('ix_meeting_action_items_status'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_meeting_id'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_assigned_to_user_id'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_assigned_to_employee_id'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_analysis_id'), table_name='meeting_action_items')
    op.drop_table('meeting_action_items')
    op.drop_index(op.f('ix_meeting_transcripts_meeting_id'), table_name='meeting_transcripts')
    op.drop_table('meeting_transcripts')
    op.drop_index(op.f('ix_meeting_speakers_meeting_id'), table_name='meeting_speakers')
    op.drop_index(op.f('ix_meeting_speakers_mapped_user_id'), table_name='meeting_speakers')
    op.drop_index(op.f('ix_meeting_speakers_mapped_employee_id'), table_name='meeting_speakers')
    op.drop_table('meeting_speakers')
    op.drop_index(op.f('ix_meeting_participants_user_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_employee_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_analyses_meeting_id'), table_name='meeting_analyses')
    op.drop_table('meeting_analyses')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###

    # Native PostgreSQL ENUM types are not dropped by drop_table.
    for _enum in (
        "meeting_status",
        "meeting_participant_role",
        "meeting_action_item_assignment_method",
        "meeting_action_item_priority",
        "meeting_action_item_status",
        "meeting_action_item_source",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum};")
