"""initial schema

Revision ID: 3785a3687963
Revises: 
Create Date: 2026-09-09 22:43:39.924108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3785a3687963'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True, comment='References job_postings.id — nullable until job postings module is active'),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('resume_path', sa.String(length=512), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'hired', 'rejected', name='candidate_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_job_posting_id'), 'candidates', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Unique role identifier, e.g. 'admin', 'hr_manager', 'employee'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable explanation of what this role can do'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='FK → roles.id — determines what this user can access'),
    sa.Column('full_name', sa.String(length=120), nullable=False, comment='Display name shown throughout the application'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary login identifier — must be unique across all users'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment="bcrypt hash of the user's password — never store plain text"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = account disabled but not deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp — NULL means the account is active'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employee_employment_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'on_leave', 'terminated', name='employee_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reported_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_system', sa.String(length=120), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'closed', name='incident_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_assigned_to'), 'incidents', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_incidents_reported_by'), 'incidents', ['reported_by'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False, comment="Job title, e.g. 'Python Backend Developer'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Full job description'),
    sa.Column('required_skills', sa.Text(), nullable=False, comment='Comma-separated required skills'),
    sa.Column('min_education', sa.String(length=100), nullable=False, comment='Minimum education level required'),
    sa.Column('experience_level', sa.Enum('entry', 'junior', 'mid', 'senior', 'lead', name='job_posting_experience_level'), nullable=False, comment='Seniority level — entry/junior means fresher-friendly scoring applies'),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='job_posting_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_created_by'), 'job_postings', ['created_by'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submitted_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='support_ticket_priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', 'escalated', name='support_ticket_status'), nullable=False),
    sa.Column('channel', sa.Enum('web', 'email', 'chat', 'api', name='support_ticket_channel'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_assigned_to'), 'support_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_submitted_by'), 'support_tickets', ['submitted_by'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_name', sa.String(length=120), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original uploaded filename'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='Path where the PDF is saved on disk'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='Plain text extracted from the PDF by PyPDF2'),
    sa.Column('ai_score', sa.Float(), nullable=True, comment='Weighted match score 0-100'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='Gemini-generated candidate summary'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='JSON list of identified strengths'),
    sa.Column('missing_skills', sa.Text(), nullable=True, comment='JSON list of skills gaps'),
    sa.Column('recommendation', sa.Enum('selected', 'hold', 'rejected', name='resume_recommendation'), nullable=True, comment='AI recommendation — HR makes the final decision'),
    sa.Column('status', sa.Enum('uploaded', 'extracted', 'analysed', 'error', name='resume_status'), nullable=False, comment='Tracks which pipeline stage this resume is in'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_email'), 'resumes', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_resumes_job_posting_id'), 'resumes', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_resumes_status'), 'resumes', ['status'], unique=False)
    # ### end Alembic commands ###

    # --- updated_at maintenance (parity with database/schema.sql) ---------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for _table in (
        "users", "employees", "job_postings", "resumes",
        "candidates", "support_tickets", "incidents",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{_table}_updated_at BEFORE UPDATE ON {_table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )

    # --- seed default RBAC roles ----------------------------------------------
    op.bulk_insert(
        sa.table(
            "roles",
            sa.column("name", sa.String),
            sa.column("description", sa.Text),
        ),
        [
            {"name": "admin",         "description": "Full system access"},
            {"name": "hr_manager",    "description": "Employee and recruitment management"},
            {"name": "support_agent", "description": "Customer support ticket handling"},
            {"name": "recruiter",     "description": "Recruitment pipeline management"},
            {"name": "employee",      "description": "Standard employee self-service access"},
            {"name": "viewer",        "description": "Read-only analytics access"},
        ],
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS set_updated_at() CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_job_posting_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_email'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_support_tickets_submitted_by'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assigned_to'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_created_by'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reported_by'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_to'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_job_posting_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###

    # Native PostgreSQL ENUM types are not dropped by drop_table — do it here.
    for _enum in (
        "candidate_status", "employee_employment_type", "employee_status",
        "incident_severity", "incident_status", "job_posting_experience_level",
        "job_posting_status", "resume_recommendation", "resume_status",
        "support_ticket_priority", "support_ticket_status", "support_ticket_channel",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum};")
