/**
 * modules/meetingIntelligence/SummaryPanel.js
 *
 * AI analysis output: summary, key discussion points, decisions.
 * Action items are rendered separately (ActionItemList).
 */

import React from 'react';

export default function SummaryPanel({ analysis }) {
  if (!analysis) return null;

  const {
    summary,
    key_points: keyPoints = [],
    decisions = [],
    sentiment,
    model_provider: provider,
    model_name: modelName,
  } = analysis;

  return (
    <section className="content-panel mi-panel">
      <h2>AI Summary</h2>

      <p className="mi-summary-text">{summary}</p>

      <div className="mi-analysis-cols">
        <div>
          <h3>Key discussion points</h3>
          {keyPoints.length ? (
            <ul className="mi-list">
              {keyPoints.map((p, i) => <li key={i}>{p}</li>)}
            </ul>
          ) : <p className="mi-muted">None extracted.</p>}
        </div>

        <div>
          <h3>Decisions</h3>
          {decisions.length ? (
            <ul className="mi-list mi-list-decisions">
              {decisions.map((d, i) => <li key={i}>{d}</li>)}
            </ul>
          ) : <p className="mi-muted">No explicit decisions recorded.</p>}
        </div>
      </div>

      <p className="mi-analysis-footer">
        {sentiment && <>Overall tone: <strong>{sentiment}</strong> · </>}
        Generated by {provider}{modelName ? ` (${modelName})` : ''}
      </p>
    </section>
  );
}
